global:
  resolve_timeout: 5m

# route:
#   group_by: ['alertname']
#   group_wait: 10s
#   group_interval: 10s
#   repeat_interval: 1h
#   receiver: 'email'
#   # routes:
#   #   - match:
#   #       alertname: Watchdog
#   #     receiver: 'web.hook'

# receivers:
# - name: 'email'
#   email_configs:
#   - smarthost: 'http://example.com/hook'
#     from: 'prometheus@homelab.lan'
#     to: 'xevis@ukr.net'
#     require_tls: falsel

route:
  receiver: 'telegram'
  routes:    
  # All alerts with severity=warning or severity=critical
  # are dispatched to the telegram receiver.
  - receiver: 'telegram'
    group_wait: 10s
    matchers:
    - severity=~"warning|critical"

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token: "6933641624:AAEGDJOsVOWh5lbblN5H4rGhC4AdkF1217E"
    chat_id: -4147787430

#  https://api.telegram.org/botINSERT_BOT_ID_HERE/getUpdates - to get chat_id
#  amtool --alertmanager.url=http://localhost:9093/ alert add alertname="Test alert" severity="warning" job="test-job" - to send test alert