---
- name: "Install dependencies for Geo Citizen app"
  hosts: servers
  become: true
  become_method: sudo
  roles:
    - {role: geocitizen, when: ansible_system =='Linux'}

- name: Install Docker Cadvisor Node Exporte
  hosts: servers
  become: true
  roles:
    - {role: deploy_exporters, when: ansible_system =='Linux'}
  
- name: Install Docker Prometheus Grafana
  hosts: grafana
  become: true
  roles:
    - {role: deploy_promgrafnode, when: ansible_system =='Linux'}