plugin: gcp_compute
projects:
  - "{{ ansible_env['GCP_PROJECT'] }}"
auth_kind: serviceaccount
service_account_file: "{{ service_account_file }}"
groups:
  servers: "'app' in name"
  grafana: "'monitoring' in name"